### ISSUE TITLE
extracting secrets via pull requests

### ISSUE THREAD

**Issue by HarryR** [lc/secretz#2]
when you submit a pull request, you can essentially run code in the travis environment with access to their full environment right?

Many tokens, secrets, passwords etc are stored in the environment, or otherwise accessible to code running on Travis.

Sometimes pull requests are built automagically for open-source projects.

2 + 2 = 4

etc.

**Comment by lc** [comment]
Haha, I like the hacker mentality but it's not super feasible in my case :) 

1. The PR would have to be approved by me
2. There's no tokens, passwords, nor anything secret in the way I have my environment setup
