### ISSUE TITLE
why am I getting this message?

### ISSUE THREAD

**Issue by smodnix** [lc/secretz#4]
`TravisCI responded with a non-200 statuscode. You're likely being rate-limited`

**Comment by 0x3c3e** [comment]
Hi, @smodnix, as I understand `Travis` has two domains `org` and `com`. Current version of `secretz` supports only `org`. Check token on https://travis-ci.org/account/preferences.
Here is related PR: https://github.com/lc/secretz/pull/1

**Comment by dzhenway** [comment]
hi @smodnix 

dont use token from `https://travis-ci.org/account/preferences`
you need install `travis` and then try to generate token `travis token --org`
finally you can setkey for `secretz` with the token

**Comment by 0x3c3e** [comment]
@dzhenway what's wrong with token from https://travis-ci.org/account/preferences?

**Comment by dzhenway** [comment]
hi @0x3c3e 

I dunno with token from that, last time when i tried use the token i got same error 
`TravisCI responded with a non-200 statuscode. You're likely being rate-limited`
So, i just installed `travis` and generate token. And then i can use your tool sir.
Maybe I wrong paste the code or anything.

**Comment by dzhenway** [comment]
hi @ 0x3c3e

By the way
when all processes have been carried out. How do I check all files that contain sensitive? manually or is there a special way?

**Comment by 0x3c3e** [comment]
@dzhenway based on the source code, `secretz` only downloads log files.

**Comment by dzhenway** [comment]
hi @0x3c3e 

Okay thank you sir

**Comment by smodnix** [comment]
@0x3c3e @dzhenway Thanks!

**Comment by insomnialord** [comment]
Hi.I have same trouble.I use token from travis token --org
parameters -c 3 -delay 900 -members scan -timeout 20 
TravisCI responded with a non-200 statuscode. You're likely being rate-limited 
Any ideas why this might happen?
and this happen with some companies, not all
Understood. This is because of -members scan

**Comment by smodnix** [comment]
@insomnialord did you check api from https://travis-ci.org/account/preferences?

**Comment by insomnialord** [comment]
> @insomnialord did you check api from https://travis-ci.org/account/preferences?
yep i tried with both tokens

**Comment by smodnix** [comment]
When you create config file did you do write like this without <> symbols?
secretz -setkey API-KEY

**Comment by insomnialord** [comment]
> When you create config file did you do write like this without <> symbols?
> secretz -setkey API-KEY

yes

**Comment by lc** [comment]
@insomnialord  this is because you're being rate-limited by TravisCI due to the high number of requests this tool generates.
